version: '3'
services:
    nginx:
        image: "bahaa129/fibo-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
           - 80:80        
    fibo-backend:
        image: "bahaa129/fibo-server"
        mem_limit: 128m
        hostname: fibo-backend
        environment:
             REDIS_HOST: $REDIS_HOST
             REDIS_PORT: $REDIS_PORT
             PGUSER: $PGUSER
             PGHOST: $PGHOST
             PGDATABASE: $PGDATABASE
             PGPASSWORD: $PGPASSWORD
             PGPORT: $PGPORT
    client:
        image: "bahaa129/fibo-frontend"
        mem_limit: 128m
        hostname: client
    worker:
        image: "bahaa129/fibo-worker"
        mem_limit: 128m
        hostname: worker
        environment:
           REDIS_HOST: $REDIS_HOST
           REDIS_PORT: $REDIS_PORT     
