version: '3'
services:
    postgress-db:
        image: postgres
        environment:
           POSTGRES_PASSWORD: Aa123456
    redis:
        image: redis
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
           - 5030:80        
    fibo-backend:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
          - /app/node_modules
          - ./server:/app    
        environment:
             REDIS_HOST: redis
             REDIS_PORT: 6379
             PGUSER: postgres
             PGHOST: postgress-db
             PGDATABASE: postgres
             PGPASSWORD: Aa123456
             PGPORT: 5432
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
          - /app/node_modules
          - ./client:/app
        environment:
            WDS_SOCKET_PORT: 0
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
          - /app/node_modules
          - ./worker:/app
        environment:
           REDIS_HOST: redis
           REDIS_PORT: 6379     
